import type { Metadata } from "next";
import { Montserrat, Roboto } from "next/font/google";
import { ReduxProvider } from "@/providers/ReduxProvider";
import "./globals.css";
import HeaderWrapper from "@/components/organisms/header/HeaderWrapper";
import FooterWrapper from "@/components/organisms/footer/FooterWrapper";
import { Toaster } from "react-hot-toast";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
});

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Favoor E-commerce website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${roboto.variable} antialiased bg-light-gray overflow-x-hidden`}
      >
        <ReduxProvider>
          <HeaderWrapper />
          {children}
          <Toaster position="top-right" reverseOrder={false} />
          <FooterWrapper />
        </ReduxProvider>
      </body>
    </html>
  );
}
